---
- name: reboot remote host
  shell: '/sbin/reboot'
  changed_when: false

- name: wait for host awakening
  local_action:
    wait_for host={{ ansible_ssh_host }}
    port={{ ansible_ssh_port }}
    delay={{ waiting_sec_for_reboot | 10 }}
    state=started
  changed_when: false
