---
- name: register epel repo
  sudo: yes
  yum:
    name: http://ftp.iij.ad.jp/pub/linux/fedora/epel/6/i386/epel-release-6-8.noarch.rpm
    state: present

- name: epel repo is enabled?
  shell: grep enabled /etc/yum.repos.d/epel.repo | grep 1 | wc -l
  register: enabled_status
  changed_when: false

- name: use enablerepo option to enable epel repo
  sudo: yes
  shell: sed -ie '/^enabled/s/1/0/' /etc/yum.repos.d/epel.repo
  when: "'0' not in enabled_status.stdout"
