---
- name: install libselinux-python to handle files
  sudo: yes
  yum:
    name: libselinux-python
    state: latest

- name: update OpenSSL to avoid Heartbleed
  sudo: yes
  yum:
    name: openssl-1.0.1e-30.el6_6.2.x86_64
    state: present
